server:
  port: 8080
# ????
spring:
  application:
    name: spring-cloud-nacos


  cloud:
    nacos:
      discovery:
        #??nacos server???
        server-addr: localhost:8848
        #元数据的设置
#        metadata:
#          instance:
